### ISSUE TITLE
Proxies not working

### ISSUE THREAD

**Issue by GhostOP1545** [notlit69/picsart-promo-gen#1]
Like when i put proxies in proxies.txt its getting error so i know its fix
Go in gen.py 
Go in line 14
remove the formatproxy 
done!

I hope its useful.

**Comment by notlit69** [comment]
formatproxy is used for formatting to proxy format which are not supported by tls_client lib ( other formats excluding host:port and user:pass@host:port ) u wont get any error if u use normal user:pass@host:port format so i advise using that
